### ISSUE TITLE
Use _.runInContext

### ISSUE THREAD

**Issue by jdalton** [dreadcast/lowerdash#1]
You should use [_.runInContext](https://lodash.com/docs#runInContext) to avoid potential conflicts with the primary npm package or other enviro for that matter.

```js
var _ = require('lodash').runInContext();
```

**Comment by dreadcast** [comment]
Hi John,
Thank you for taking a look at my code.
Lowerdash is made of various pieces of code that I mixed into an underscore mixin. I've recently switched to lodash which seems better and full featured ! Moreover,  I've just noticed that at least one of my method is a duplicate of yours which wasn't present in underscore.

I will try `runInContext()` soon !

**Comment by jdalton** [comment]
Rock!
